// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/repos/discussions": {
            "get": {
                "description": "get discussions from GitHub",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GitHub"
                ],
                "summary": "get discussions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.Discussion"
                            }
                        }
                    }
                }
            }
        },
        "/repos/issues": {
            "get": {
                "description": "get issues from GitHub",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GitHub"
                ],
                "summary": "get issues",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search by",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.Issue"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.Discussion": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/service.User"
                },
                "category_name": {
                    "type": "string"
                },
                "comment_count": {
                    "type": "integer"
                },
                "comment_users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.User"
                    }
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_answered": {
                    "type": "boolean"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.Label"
                    }
                },
                "thumbs_up": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "upvote_count": {
                    "type": "integer"
                }
            }
        },
        "service.Issue": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/service.User"
                },
                "comment_count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.Label"
                    }
                },
                "thumbs_up": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "service.Label": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "service.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
