package model

import (
	"bytes"
	"encoding/json"
	"net/http"
	"regexp"

	"gorm.io/gorm/clause"

	"chaitin.cn/patronus/safeline-2/management/webserver/pkg/config"

	"chaitin.cn/patronus/safeline-2/management/webserver/pkg"
	"chaitin.cn/patronus/safeline-2/management/webserver/pkg/constants"
	"chaitin.cn/patronus/safeline-2/management/webserver/pkg/database"
	"chaitin.cn/patronus/safeline-2/management/webserver/utils"
)

type Options struct {
	Base
	Key   string `gorm:"column:key;uniqueIndex"`
	Value string `gorm:"column:value;"`
}

func initOptions() error {
	db := database.GetDB()

	// The session signing key authorises every management request, so it has
	// to come from a cryptographically secure source.
	secretKey := Options{Key: constants.SecretKey, Value: utils.RandHex(32)}
	db.Clauses(clause.OnConflict{DoNothing: true}).Create(&secretKey)

	machineId := Options{Key: constants.MachineID, Value: utils.RandStr(32)}
	_ = db.Clauses(clause.OnConflict{DoNothing: true}).Create(&machineId)
	go NotifyInstallation(machineId.Value)

	return rotatePredictableSecretKey()
}

// predictableSecretKeyPattern matches the shape of a key produced by the
// former RandStr: 32 letters out of [a-zA-Z]. RandHex produces 64 hexadecimal
// characters, so a value matching this pattern can only come from the
// predictable generator.
var predictableSecretKeyPattern = regexp.MustCompile(`^[a-zA-Z]{32}$`)

// rotatePredictableSecretKey replaces a session signing key that was generated
// with the predictable time seeded PRNG.
//
// The key is only created when it is missing (OnConflict DoNothing), so an
// installation that was set up by an older release keeps its weak value
// forever. Such a key has to be treated as public: it is rotated here, which
// invalidates the sessions that were signed with it, and the administrator
// simply logs in again.
func rotatePredictableSecretKey() error {
	db := database.GetDB()

	var secretKey Options
	if err := db.Where(&Options{Key: constants.SecretKey}).First(&secretKey).Error; err != nil {
		return err
	}

	if !predictableSecretKeyPattern.MatchString(secretKey.Value) {
		return nil
	}

	logger.Warn("The session signing key was generated by a predictable random source, rotating it. Existing sessions are invalidated.")
	secretKey.Value = utils.RandHex(32)

	return db.Save(&secretKey).Error
}

func NotifyInstallation(machineId string) {
	logger.Info("Notify installation")
	tr := pkg.TelemetryRequest{
		Telemetry: pkg.TelemetryInfo{
			Id: constants.TelemetryId,
		},
		Safeline: pkg.SafelineInfo{
			Id:      machineId,
			Type:    constants.Installation,
			Version: constants.Version,
		},
	}
	data, err := json.Marshal(tr)
	if err != nil {
		logger.Error(err)
		return
	}

	reader := bytes.NewReader(data)
	rsp, err := pkg.DoPostTelemetry(utils.GetHTTPClient(), config.GlobalConfig.Telemetry.Addr, reader)
	if err != nil {
		logger.Error(err)
		return
	}
	// The caller owns the response returned by DoPostTelemetry and has to
	// release it, otherwise every report leaks a connection.
	defer rsp.Body.Close()

	if rsp.StatusCode != http.StatusOK && rsp.StatusCode != http.StatusCreated {
		logger.Errorf("transfer telemetry %s failed, status code = %d", constants.Installation, rsp.StatusCode)
		return
	}
}
